update Landmarks set GPSCoord = geography::Point(39.47419, -77.74457, 4748) where LandmarkId = 11;

insert into landmarks values ('C-2', 'World''s First Public Passenger Flight', 'On September 9, 1908, near this site, Orville Wright carried aloft in public his first passenger, Lt. Frank P. Lahm, for a flight lasting 6 minutes and 24 seconds.  Three days later, he took Major George O. Squier on a flight of 9 minutes and 6 seconds durection.  From this primitive beginning has evolved an air transportation system that today spans the globe.', 'USA', 'Virginia', geography::Point(38.881039, -77.083931, 4748),3,GETUTCDATE());

insert into landmarks values ('C-7', 'Orville Wright''s First Virginia Flight', 'Orville Wright made his first hevier-than-air flight in Virginia at Fort Myer for the U.S. Army on 3 September, 1908.  He flew the plane slightly more than a minute, reaching a speed of 40 miles per hour.  During the next two weeks here, Wright broke world records for speed and time spent in the air for a heavier-than-air craft.  On 17 September 1908, however the plane crashed, killing Lt. Thomas Selfridge and injuring Wright.  In 1909, the Wright brothers returned to Fort Myer.  After additional flight tests, the Army bought their plane for $25,000 on July 1909 for its first military aircraft.', 'USA', 'Virginia', geography::Point(38.881039, -77.083931, 4748),3,GETUTCDATE());

insert into landmarks values (NULL, 'Mary Carlin House', 'This home incorporates the original log house built about 1800 by William Carlin.  It is one of the earliest structures remaining in Arlington.  At one time, Carlin had been a tailor in Alexandria, whose clients included George Washington. Mr. Carlin''s grand-daughter, Mary Anexander Carlin, a school teacher, was born in this house and lived here until her death in 1905.  Hers was the last burial in the Ball-Carlin Cemtery adjacent  to the Glencarlyn Libary.', 'USA', 'Virginia', geography::Point(38.869164, -77.126622, 4748),3,GETUTCDATE());

--insert into landmarks values ('','','','USA','Virginia',geography::Point(, 4748),3,GETUTCDATE());

insert into landmarks values (NULL,'Test','This is a test','USA','Virginia',geography::Point(38.852, -77.128, 4748),3,GETUTCDATE());

SELECT *
FROM sys.spatial_reference_systems
where unit_of_measure = 'foot';

exec dbo.getLocalLandmarks @longitude = 38.873658, @latitude = -77.147724, @distance = 5;

select LandmarkId, MarkerNumber, Title, Description, Country, StateProvince, GPSCoord.ToString() as GPSCoord, CreatedBy, CreatedDate from Landmarks where Country = 'USA' and StateProvince = 'Virginia';

-- vero
insert into landmarks values (NULL,	'US-1 Tee-Beam Bridge in Indian River County','The tee-beam bridge at this location carried traffic southbound on US-1 over the Florida East Coast Railway and Old Dixie Highway beginning in 1927. The tee-beam design, constructed from cast-in-place concrete beams and reinforced steel running lengthwise along the bottom, was one of the most popular bridge types in the 1920s and 1930s. The Florida State Road Department was authorized in 1923 to complete a system of roads designated by the state legislature to help encourage tourism, which included the construction of US-1 as a major north-south route through Florida. This tee-beam bridge was the first US-1 bridge constructed by the Florida State Road Department in Indian River County. It was the second of six bridges built in the 1920s along US-1 in Florida. The durable tee-beam bridge was easy and cost-effective to build. This bridge was also important for its great length for a tee-beam bridge, which totaled 288 feet. The bridge at this location was a significant example from the 1920s, a decade from which historic bridges are increasingly rare. It was replaced in 2014.','USA','Florida',geography::Point(27.556022,-80.369530,4748),3,GETUTCDATE());
insert into landmarks values (NULL,	'Winter-Time Ais Indian Town of Pentoaya','In 1605 Florida''s Spanish Governor Pedro de Ybarra sent Lt. Alvaro Mexia on a diplomatic mission to the Ais Indians. Mexia recorded his passage from St. Augustine down the coast to the principal Ais Indian town near present-day Vero Beach. At the confluence of Ulumay Lagoon (Banana River Lagoon) and the Great Bay of Ais (Indian River Lagoon) Mexia reported the location of the "winter-time" Ais Indian Town of Pentoaya. He recorded that the 17th century town of Pentoaya was located "directly opposite on the western mainland," near the confluence of the Eau Gallie and the Indian Rivers. The Winter-Time Town of Pentoaya was located between this park and the Banana River Lagoon, to the west. It consisted of a complex of shell middens, mounds and a causeway, which divided the small lake seen from this marker. Little remains of these mounds, as the shells found in them were used as roadbed material early in the 20th century. A Florida Heritage Site.','USA','Florida',geography::Point(28.142879,-80.597613,4748),3,GETUTCDATE());
insert into landmarks values (NULL,	'Bethel Creek House of Refuge','The first house of refuge was completed on February 28, 1876, built by the United States Life-Saving Service. This house was to provide a safe haven for those shipwrecked along the then desolate coast of Florida. During World War II, the Coast Guard took over the station and built a 40 foot observation tower to watch for submarines.','USA','Florida',geography::Point(27.665248, -80.359214,4748),3,GETUTCDATE());
insert into landmarks values (NULL,	'Birthplace For Equal Suffrage For Women in Florida','''population of Fellsmere is of a high type of intelligence, with lofty ideals and wise execution. Progressive in all things, perhaps no better indication of the fact may be given than the unanimous vote of the town granting unrestricted suffrage to women.'' Fellsmere Tribune, March 8, 1916. In the June 19, 1915 city election, Mrs. Zena M. Dreier was the first woman to cast a ballot in Fellsmere, in all of Florida, and south of the Mason-Dixon Line. The town residents took much pride in this unique woman''s right, and urged neighboring municipalities to follow the ''Fellsmere Way'' to equal suffrage. In 1919, a U.S. Constitutional amendment granted suffrage to women. But history will note that Fellsmere led the way.','USA','Florida',geography::Point(27.770433,-80.601134,4748),3,GETUTCDATE());
insert into landmarks values (NULL,	'Breconshire Marker','The Breconshire was an iron steamship that was built in 1883. On the night of April 29th, it ran aground in 20 feet of water due to faulty navigational charts. The Coast Guard, responding to the call of distress, attempted to tow the steamer off the reef, but the Breconshire began taking on water. On April 30th, the order was issued to abandon ship. No lives were lost, and at low tide, the boiler of the ship is still visible from Humiston Park.','USA','Florida',geography::Point(27.651683,-80.354830,4748),3,GETUTCDATE());
insert into landmarks values (NULL,	'Captain Forster Hammock Preserve','A 110-acre preserve, which contains one of the largest remaining maritime hammocks on Orchid Island and was home to Captain Frank Forster. Forester was one of the first Orchid Island residents, he established a post office, which he called Orchid and became the first postmaster in 1887. A one-room school, the Orchid School, was located on his homestead.','USA','Florida',geography::Point(27.757418,-80.403177,4748),3,GETUTCDATE());

-- clifton
use Landmark;
insert into landmarks values (NULL,	'"Pink House"','The house was built by the Ambler family who maintained a farm outside of town where they grew various crops. In the 1960''s a business located here painted the building pink and it has been known by locals ever since as the “Pink” House.','USA','Virginia',geography::Point(38.780462,-77.38743,4748),3,GETUTCDATE());
insert into landmarks values (NULL,	'Bradley House','Owned by Rev. Wm. Bradley & his wife Elisabeth, the first Presbyterian Minister in Clifton, the parents of Margaret Riviere Hetzel, who taught the first School in Clifton.  Restored in 1981.','USA','Virginia',geography::Point(38.781342, -77.384166,4748),3,GETUTCDATE());
